### ISSUE TITLE
Feature Request: Local Installation with k3s Support for HorizonCD

### ISSUE THREAD

**Issue by cubxxw** [horizoncd/horizon#100]
## Background

HorizonCD is a platform for continuous delivery and deployment that supports multiple deployment targets. Currently, HorizonCD only supports Kubernetes(minikube、kind) as a deployment target, but there is a growing demand for support of local installations.

## Objective

The objective of this feature request is to add support for local installations using k3s, a lightweight Kubernetes distribution that is optimized for production workloads in resource-constrained environments.

## Design

The following table outlines the design considerations for this feature request:

| Design Consideration | Description                                                  |
| -------------------- | ------------------------------------------------------------ |
| Compatibility        | Investigate if k3s meets the business requirements of HorizonCD |
| HorizonCD Version    | Choose the most appropriate version of HorizonCD to support local installations with k3s |
| Container Runtime    | Choose the appropriate CRI (Docker or Containerd) for the local installation |
| Helm Controller      | Determine if the Helm controller is required for installation or if it can be installed without the Helm CLI |

## Implementation Steps

The following steps will be taken to implement this feature request:

| Implementation Steps          | Description                                                  |
| ----------------------------- | ------------------------------------------------------------ |
| k3s Installation Script       | Develop an installation script to deploy k3s                 |
| HorizonCD Directory Structure | Choose an appropriate directory structure for HorizonCD on the local installation |
| Docker Installation           | Determine if Docker is required for the local installation   |
| Makefile Deployment           | Develop a Makefile for one-click deployment of the local installation |

## Tasks

The current horizonci has a lot to improve in testing and CI, count the PR

 

| Type        | Improvements                                                 | Issue | PR   | Status |      |
| ----------- | ------------------------------------------------------------ | ----- | ---- | ------ | ---- |
| Makefile    | Give the help information of Makefile to make it more readable, give some necessary lab |       | #65  | ✅      |      |
| k3s-install | Suitable for developer local lightweight installation        |       |      | ❌      |      |

⚠️ Please note that this feature request is currently being discussed on the [HorizonCD GitHub Discussions forum](https://github.com/horizoncd/horizon/discussions/81).

**Comment by cubxxw** [comment]
The current project has the following shortcomings:

+ [ ] The Makefile has too simple functionality, weak extensibility, does not support cross-compilation and container compilation, and does not support other extension capabilities.
+ [ ] There is no good handling of logs (can be encapsulated with zap).
+ [ ] There is no good handling of copyright.
+ [ ] There is no perfect CICD process.
+ [ ] The robot setting is unreasonable.
+ [ ] There is no suitable error code design solution.
+ [ ] Although there is Swagger, API documentation is not generated.
+ [ ] There is no elegant tag, branch, release, and commit specification.
+ [ ] The documentation is not elegant enough.
+ [ ] Unit coverage should be used, embedded in actions and Makefiles
